### ISSUE TITLE
Everything is shown

### ISSUE THREAD

**Issue by Meebsy** [srhinos/new-openables#14]
No errors produced, but everything in your bags, and everything you pick up now shows. That is alot of perm blacklisting atm.

**Comment by fr0z3night** [comment]
yea same problem, reloading the ui does seem to put a bandaid on the problem and stop it showing everything, must be something with the initial load.

**Comment by Bartyx** [comment]
Same problem. Everything is showing up and ignore does not working. After relog, everything will shows up again.

**Comment by srhinos** [comment]
Yeah, open to accepting a PR here to fix it if anyone wants to put the time in!

**Comment by Kyphala** [comment]
Have the same problem but it doesn't appear for all chars.

**Comment by MaxStyle75** [comment]
Hello
In file nop-data.lua at line 79 replace 
`  [127799] = {{1,PRI_TOKEN},4,nil,nil}, -- Baleful Pendant, for another slots than armor.`
by
`  [127799] = {{1,PRI_TOKEN},3,nil,nil}, -- Baleful Pendant, for another slots than armor.`

**Comment by fr0z3night** [comment]
Thanks for that, seems to have done the job, logged in on 2 different accounts and no NOP showing up with random items.  Just shows how one little thing can make the whole addon go haywire. Thanks again Max

> Hello
> In file nop-data.lua at line 79 replace
> ` [127799] = {{1,PRI_TOKEN},4,nil,nil}, -- Baleful Pendant, for another slots than armor.`
> by
> ` [127799] = {{1,PRI_TOKEN},3,nil,nil}, -- Baleful Pendant, for another slots than armor.`

**Comment by yoshimo** [comment]
@srhinos  i think we can close this now
