### ISSUE TITLE
Project package is corrupted or incorrectly packaged.

### ISSUE THREAD

**Issue by Kaboca** [srhinos/new-openables#3]
CurseBreaker v3.14.1 -> RuntimeError: Failed to parse addon data: new-openables.

**Comment by srhinos** [comment]
ah fuck I know what the problem is

**Comment by srhinos** [comment]
Updated deploy script, thanks for pointing this out. Wouldn't have noticed since WoWUp doesn't throw an error for this. Verified that it deploys in the manor that WoWUp and CurseBreaker would expect, for wowup users, you may need to delete garbage folders out of your addon directory as I had to :(

**Comment by Kaboca** [comment]
Perfect. :) Thanks!
