### ISSUE TITLE
TOC version does not match release version

### ISSUE THREAD

**Issue by puppysnuff** [srhinos/new-openables#6]
The TOC version doesn't match the release version, this causes addon managers to constantly think the addon is out of date:

![image](https://user-images.githubusercontent.com/48777436/100957412-3828ba80-34cf-11eb-92cc-730657d4d3d2.png)

**Comment by fitsou** [comment]
I second that.
The app we are using for addon updates is Ajour.
it would be nice to hotfix it

**Comment by BanditTech** [comment]
I am using WoWup without an issues, it does not consider the TOC version and instead bases the update on the date the addon was last changed. Maybe consider switching to a better app? :P

**Comment by srhinos** [comment]
> 
> 
> I am using WoWup without an issues, it does not consider the TOC version and instead bases the update on the date the addon was last changed. Maybe consider switching to a better app? :P
> 
> Although updating the toc would not hurt hehe

Agree with this but I'll bump toc when I get a chance, I really wanna take a crack at rewriting a big portion of this addon because the code is so dogshit its impossible to maintain

**Comment by BanditTech** [comment]
I recently started a full rebase of my Frankenstein script, and it's very refreshing. Especially since I started the project as a novice, the code really showed. I was trapped in old ways, until I finally just got tired of tracking down bugs! Hehe totally feel you man
